### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by 6543** [6543/batmon#3]
Candidates:
![image-7](https://github.com/6543/batmon/assets/24977596/15fb513a-e638-455d-ae2f-8db36419c154)
![image-6](https://github.com/6543/batmon/assets/24977596/b1933153-363e-43d9-8c73-9ac901349728)
![image-1](https://github.com/6543/batmon/assets/24977596/d09da44f-0c7f-4c0a-850c-501eb2d44e77)

**Comment by mondlicht-und-sterne** [comment]
Kandidat 1 gefällt mir am besten
